# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lefestin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='product_pic',
            field=models.ImageField(blank=True, upload_to='recipes'),
        ),
    ]
