# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lefestin', '0002_auto_20160728_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='photo',
            field=models.ImageField(default='default_group.jpg', upload_to='group_photos'),
        ),
    ]
