# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lefestin', '0003_auto_20160728_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lefestin.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='photo',
            field=models.ImageField(default='images/default_group.jpg', upload_to='group_photos'),
        ),
    ]
